// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ustvmgixjpjedemwjqwp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVzdHZtZ2l4anBqZWRlbXdqcXdwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3MzQxMzAsImV4cCI6MjA3MDMxMDEzMH0.QSUdzuya_oTPSXg1EaD1pNTs7XJXiE8QSukc79LRjPU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});